CREATE TABLE IF NOT EXISTS auctions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  seller_id INT NOT NULL,
  category_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  starting_price DECIMAL(12,2) NOT NULL,
  reserve_price DECIMAL(12,2),
  current_bid DECIMAL(12,2) DEFAULT 0.00,
  min_bid_increment DECIMAL(10,2) DEFAULT 1.00,
  bid_count INT DEFAULT 0,
  state ENUM('DRAFT','SCHEDULED','LIVE','EXTENDING','ENDED','SETTLING','COMPLETED') DEFAULT 'DRAFT',
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  original_end_time DATETIME NOT NULL,
  anti_snipe_seconds INT DEFAULT 30,
  extension_seconds INT DEFAULT 120,
  winner_id INT,
  version INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories(id),
  FOREIGN KEY (winner_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_state (state),
  INDEX idx_seller (seller_id),
  INDEX idx_category (category_id),
  INDEX idx_end_time (end_time),
  INDEX idx_state_end (state, end_time),
  FULLTEXT INDEX ft_search (title, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
